import JSZip from 'jszip';
import { triggerDownload, processImage } from './imageProcessor';
import { IconSpecification, androidIconRequirements } from '../config/storeRequirements/androidIcons';
import { iosIconRequirements } from '../config/storeRequirements/iosIcons';

export interface IconExportItem {
  spec: IconSpecification;
  blob: Blob;
}

export async function exportIconPackageZip(
  platform: 'ios' | 'android' | 'all',
  items: IconExportItem[],
  appName = 'AppAssets'
): Promise<void> {
  const zip = new JSZip();

  if (platform === 'ios' || platform === 'all') {
    const iosFolder = zip.folder('iOS/AppIcon.appiconset');
    
    // Create Xcode valid Contents.json
    const contentsJson = {
      images: items
        .filter(item => item.spec.platform === 'ios')
        .map(item => ({
          size: `${item.spec.size}x${item.spec.size}`,
          idiom: item.spec.name.toLowerCase().includes('ipad') ? 'ipad' : 
                 item.spec.name.toLowerCase().includes('watch') ? 'watch' : 
                 item.spec.category === 'store' ? 'ios-marketing' : 'iphone',
          filename: item.spec.filename,
          scale: item.spec.scale || '1x'
        })),
      info: {
        version: 1,
        author: 'App Asset Studio'
      }
    };

    if (iosFolder) {
      iosFolder.file('Contents.json', JSON.stringify(contentsJson, null, 2));
      for (const item of items.filter(i => i.spec.platform === 'ios')) {
        iosFolder.file(item.spec.filename, item.blob);
      }
    }
  }

  if (platform === 'android' || platform === 'all') {
    const androidFolder = zip.folder('Android');
    if (androidFolder) {
      for (const item of items.filter(i => i.spec.platform === 'android')) {
        // e.g. res/mipmap-xxhdpi/ic_launcher.png or playstore/play_store_512.png
        androidFolder.file(`${item.spec.folderPath}/${item.spec.filename}`, item.blob);
      }

      // Add a helpful README.txt for developers explaining how to drag into Android Studio
      androidFolder.file(
        'README.txt',
        `Android App Assets
Generated by App Asset Studio
=============================
- Copy the 'res' folder into your Android project 'app/src/main/res/' directory.
- Use 'playstore/play_store_icon_512.png' for your Google Play Console store listing.
- Use 'playstore/feature_graphic_1024x500.png' as your store listing promotional banner.`
      );
    }
  }

  const content = await zip.generateAsync({ type: 'blob' });
  triggerDownload(content, `${appName}-${platform}-icons.zip`);
}

export async function exportAppIconsZip(
  masterImg: HTMLImageElement,
  appName = 'AppAssets',
  fillSolidBg = true,
  bgColor = '#0f172a'
): Promise<void> {
  const allSpecs: IconSpecification[] = [
    ...iosIconRequirements.icons,
    ...androidIconRequirements.icons
  ];

  const exportItems: IconExportItem[] = [];

  for (const spec of allSpecs) {
    const res = await processImage(masterImg, {
      width: spec.width,
      height: spec.height,
      format: 'image/png',
      quality: 0.95,
      corners: { topLeft: 0, topRight: 0, bottomRight: 0, bottomLeft: 0 },
      removeTransparency: fillSolidBg && !spec.hasAlpha,
      solidBackgroundColor: bgColor
    });
    exportItems.push({
      spec,
      blob: res.blob
    });
  }

  await exportIconPackageZip('all', exportItems, appName);
}

export async function exportScreenshotsZip(
  screenshots: Array<{ filename: string; blob: Blob }>,
  bundleName = 'store-screenshots'
): Promise<void> {
  const zip = new JSZip();
  screenshots.forEach(sc => {
    zip.file(sc.filename, sc.blob);
  });
  const content = await zip.generateAsync({ type: 'blob' });
  triggerDownload(content, `${bundleName}.zip`);
}

export async function exportBatchImagesZip(
  images: Array<{ filename: string; blob: Blob }>,
  zipName = 'resized-images.zip'
): Promise<void> {
  const zip = new JSZip();
  // Ensure unique filenames inside zip
  const nameCounts = new Map<string, number>();
  images.forEach(img => {
    let finalName = img.filename;
    if (nameCounts.has(finalName)) {
      const count = nameCounts.get(finalName)! + 1;
      nameCounts.set(finalName, count);
      const dotIdx = finalName.lastIndexOf('.');
      if (dotIdx !== -1) {
        finalName = `${finalName.substring(0, dotIdx)}-${count}${finalName.substring(dotIdx)}`;
      } else {
        finalName = `${finalName}-${count}`;
      }
    } else {
      nameCounts.set(finalName, 0);
    }
    zip.file(finalName, img.blob);
  });
  const content = await zip.generateAsync({ type: 'blob' });
  triggerDownload(content, zipName);
}
