import { ScreenshotRequirement } from './googlePlay';

export interface AppStoreConfig {
  officialSource: string;
  officialSourceUrl: string;
  lastUpdated: string;
  version: string;
  requirements: ScreenshotRequirement[];
}

export const appStoreRequirements: AppStoreConfig = {
  officialSource: "Apple Developer - App Store Connect Help: Screenshot specifications",
  officialSourceUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications",
  lastUpdated: "2026-09-01",
  version: "iOS 18 / 2026.4",
  requirements: [
    {
      id: "apple-iphone-6-9-portrait",
      name: "iPhone 6.9\" Display (iPhone 16 Pro Max)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1320,
      height: 2868,
      minWidth: 1320,
      maxWidth: 1320,
      minHeight: 2868,
      maxHeight: 2868,
      aspectRatioDesc: "Exact 1320 x 2868 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "App Store Connect requires exact pixel match. RGB 72 DPI, flattened, no alpha.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-9-landscape",
      name: "iPhone 6.9\" Display Landscape (iPhone 16 Pro Max)",
      deviceCategory: "phone",
      orientation: "landscape",
      width: 2868,
      height: 1320,
      minWidth: 2868,
      maxWidth: 2868,
      minHeight: 1320,
      maxHeight: 1320,
      aspectRatioDesc: "Exact 2868 x 1320 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Landscape orientation for iPhone 16 Pro Max.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-7-portrait",
      name: "iPhone 6.7\" Display (iPhone 15 Pro Max, 15 Plus, 14 Pro Max)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1290,
      height: 2796,
      minWidth: 1290,
      maxWidth: 1290,
      minHeight: 2796,
      maxHeight: 2796,
      aspectRatioDesc: "Exact 1290 x 2796 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Standard primary large iPhone requirement in App Store Connect.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-7-landscape",
      name: "iPhone 6.7\" Display Landscape (iPhone 15 Pro Max, 14 Pro Max)",
      deviceCategory: "phone",
      orientation: "landscape",
      width: 2796,
      height: 1290,
      minWidth: 2796,
      maxWidth: 2796,
      minHeight: 1290,
      maxHeight: 1290,
      aspectRatioDesc: "Exact 2796 x 1290 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Landscape screenshot for 6.7\" iPhones.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-5-portrait",
      name: "iPhone 6.5\" Display (iPhone 11 Pro Max, XS Max, XR)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1242,
      height: 2688,
      minWidth: 1242,
      maxWidth: 1242,
      minHeight: 2688,
      maxHeight: 2688,
      aspectRatioDesc: "Exact 1242 x 2688 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Earlier generation notch iPhone 6.5\" display.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-3-portrait",
      name: "iPhone 6.3\" Display (iPhone 16 Pro)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1206,
      height: 2622,
      minWidth: 1206,
      maxWidth: 1206,
      minHeight: 2622,
      maxHeight: 2622,
      aspectRatioDesc: "Exact 1206 x 2622 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Native resolution for iPhone 16 Pro.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-6-1-portrait",
      name: "iPhone 6.1\" Display (iPhone 15, 15 Pro, 14, 14 Pro, 13 Pro)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1179,
      height: 2556,
      minWidth: 1179,
      maxWidth: 1179,
      minHeight: 2556,
      maxHeight: 2556,
      aspectRatioDesc: "Exact 1179 x 2556 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Standard 6.1\" Super Retina XDR display.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-iphone-5-5-portrait",
      name: "iPhone 5.5\" Display (iPhone 8 Plus, 7 Plus, 6s Plus)",
      deviceCategory: "phone",
      orientation: "portrait",
      width: 1242,
      height: 2208,
      minWidth: 1242,
      maxWidth: 1242,
      minHeight: 2208,
      maxHeight: 2208,
      aspectRatioDesc: "Exact 1242 x 2208 pixels required by Apple",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Legacy home button 16:9 iPhone display tier.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-ipad-13-portrait",
      name: "iPad Pro 13\" (M4) / iPad Pro 12.9\" Display",
      deviceCategory: "tablet_10",
      orientation: "portrait",
      width: 2064,
      height: 2752,
      minWidth: 2048,
      maxWidth: 2064,
      minHeight: 2732,
      maxHeight: 2752,
      aspectRatioDesc: "2064 x 2752 or 2048 x 2732 pixels",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Required for all Universal and iPad apps.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-ipad-13-landscape",
      name: "iPad Pro 13\" (M4) / 12.9\" Landscape",
      deviceCategory: "tablet_10",
      orientation: "landscape",
      width: 2752,
      height: 2064,
      minWidth: 2732,
      maxWidth: 2752,
      minHeight: 2048,
      maxHeight: 2064,
      aspectRatioDesc: "2752 x 2064 or 2732 x 2048 pixels",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Landscape orientation for iPad Pro 13\".",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-ipad-11-portrait",
      name: "iPad Pro 11\" Display / iPad Air",
      deviceCategory: "tablet_10",
      orientation: "portrait",
      width: 1668,
      height: 2388,
      minWidth: 1640,
      maxWidth: 1668,
      minHeight: 2360,
      maxHeight: 2388,
      aspectRatioDesc: "1668 x 2388 or 1640 x 2360 pixels",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Standard modern 11\" iPad resolution.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    },
    {
      id: "apple-watch-ultra",
      name: "Apple Watch Ultra (410 x 502)",
      deviceCategory: "wear",
      orientation: "portrait",
      width: 410,
      height: 502,
      minWidth: 410,
      maxWidth: 410,
      minHeight: 502,
      maxHeight: 502,
      aspectRatioDesc: "Exact 410 x 502 pixels",
      allowedFormats: ["image/png", "image/jpeg"],
      maxFileSizeMB: 10,
      notes: "Required for Apple Watch standalone apps.",
      officialDocUrl: "https://developer.apple.com/help/app-store-connect/reference/screenshot-specifications"
    }
  ]
};
